### ISSUE TITLE
Add support 'MAJOR.MINOR' or 'MAJOR' pattern for 'version' field

### ISSUE THREAD

**Issue by hwhsu1231** [dokempf/doxygen-install#5]
### Feature Request

Hello, author of doxygen-install.

I hope that this GitHub Action can support 'MAJOR.MINOR' or 'MAJOR' pattern for 'version' field.

Just like what the following GitHub Actions support:

- [actions/setup-python](https://github.com/actions/setup-python)
- [actions/setup-node](https://github.com/actions/setup-node)
- [jwlawson/actions-setup-cmake](https://github.com/jwlawson/actions-setup-cmake)

For example. Suppose that:

- the latest `1.y.z` release of Doxygen is `1.11.0`
- the latest `1.11.z` release of Doxygen is `1.11.0`
- the latest `1.10.z` release of Doxygen is `1.10.0`
- the latest `1.9.z` release of Doxygen is `1.9.8`

I hope that this GitHub Action can automatically compute what the latest release the given pattern version is:

- To install the latest `1.y.z` release of Doxygen:

   ```yml
   - uses: ssciwr/doxygen-install@v1
     with:
       version: "1"
   ```

   We can get `1.11.0` release of Doxygen installed.

- To install the latest `1.11.z` release of Doxygen:

   ```yml
   - uses: ssciwr/doxygen-install@v1
     with:
       version: "1.11"
   ```

   We can get `1.11.0` release of Doxygen installed.

- To install the latest `1.10.z` release of Doxygen:

   ```yml
   - uses: ssciwr/doxygen-install@v1
     with:
       version: "1.10"
   ```

   We can get `1.10.0` release of Doxygen installed.

- To install the latest `1.9.z` release of Doxygen:

   ```yml
   - uses: ssciwr/doxygen-install@v1
     with:
       version: "1.9"
   ```

   We can get `1.9.8` release of Doxygen installed.

### Versions

- doxygen-install: `v1.5.0`
